version: '3.4'

services:

  webapi:
    container_name: sampleapp-api
    image: sampleapp-api
    build:
      context: .
      dockerfile: src/SampleApp.Api/Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - sample-api-network
    depends_on:
      mssql:
        condition: service_healthy

  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    container_name: mssql
    environment:
      SA_PASSWORD: 'Dev@123456'
      ACCEPT_EULA: 'Y'
    ports:
      - 1433:1433
    networks:
      - sample-api-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Dev@123456" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  sample-api-network:
    name: sample-api-network
